---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/accounts/":
    get:
      summary: Список всех аккаунтов
      tags:
      - Accounts API
      responses:
        '200':
          description: Список аккаунтов
          content: {}
  "/accounts/{account_number}":
    get:
      summary: Запрос информации по аккаунту
      tags:
      - Accounts API
      parameters:
      - name: account_number
        in: path
        description: Номер счета
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Информация об аккаунте
          content:
            application/json:
              schema:
                type: object
                properties:
                  account:
                    type: object
                    parameters:
                      balance:
                        type: integer
                      account_number:
                        type: string
                  status:
                    type: string
                required:
                - status
            application/xml:
              schema:
                type: object
                properties:
                  account:
                    type: object
                    parameters:
                      balance:
                        type: integer
                      account_number:
                        type: string
                  status:
                    type: string
                required:
                - status
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: rest-bank.netlify.ru
