---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/accounts/":
    get:
      summary: Список всех аккаунтов
      tags:
      - Accounts API
      responses:
        '200':
          description: Список аккаунтов
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  accounts:
                    type: array
                    required: false
                    items:
                      type: object
                      properties:
                        balance:
                          type: integer
                        account_number:
                          type: string
    post:
      summary: Создание аккаунта
      tags:
      - Accounts API
      parameters: []
      responses:
        '200':
          description: Создание нового аккаунта
          content: {}
  "/accounts/{account_number}":
    get:
      summary: Запрос информации по аккаунту
      tags:
      - Accounts API
      parameters:
      - name: account_number
        in: path
        description: Номер счета
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Информация об аккаунте
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  account:
                    type: object
                    properties:
                      balance:
                        type: integer
                      account_number:
                        type: string
                required:
                - status
  "/transfers":
    post:
      summary: Перевод средств между аккаунтами
      tags:
      - Transfer API
      parameters: []
      responses:
        '200':
          description: Перевод cредств между аккаунтами
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  transfer:
                    type: object
                    properties:
                      source_account_number:
                        type: string
                      source_balance:
                        type: integer
                      destination_account_number:
                        type: string
                      destination_balance:
                        type: integer
                      amount:
                        type: integer
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: rest-bank.netlify.ru
