---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/accounts/":
    get:
      summary: Список всех аккаунтов
      tags:
      - Accounts API
      description: "\n### Возвращает список всех созданных аккаунтов\n        \nВозможные
        значения status\n  - ok - все ok\n    \n      \naccounts - cодержит список
        всех аккаутов\n"
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  accounts:
                    type: array
                    required: false
                    items:
                      type: object
                      properties:
                        balance:
                          type: integer
                        account_number:
                          type: string
    post:
      summary: Создание аккаунта
      tags:
      - Accounts API
      description: "\n### Создает новый аккаунт с заданным номером и начальным балансом\n\naccount_number
        должен быть уникальным, balance - положительным\n  \nВозможные значения status\n
        \ - ok - все ok\n  - account_number - аккаунт с таким номером уже есть\n  -
        balance - недопустимое значение баланса\n\naccount - информация по созданному
        аккаунту\n"
      parameters:
      - name: account_number
        in: query
        description: Номер счета
        schema:
          type: string
      - name: balance
        in: query
        description: Начальный баланс
        schema:
          type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  account:
                    type: object
                    properties:
                      balance:
                        type: integer
                      account_number:
                        type: string
  "/accounts/{account_number}":
    get:
      summary: Запрос информации по аккаунту
      tags:
      - Accounts API
      description: "\n### Возвращает информацию об аккаунте\n  \nВозможные значения
        status\n  - ok - все ok\n  - account_number - аккаунт не найден\n"
      parameters:
      - name: account_number
        in: path
        description: Номер счета
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  account:
                    type: object
                    properties:
                      balance:
                        type: integer
                        description: Актуальный баланс аккаунта
                      account_number:
                        type: string
                        description: Номер аккаунта
                required:
                - status
  "/transfers":
    post:
      summary: Перевод средств между аккаунтами
      tags:
      - Transfer API
      description: "\n### Перевод средств между аккаунтами\n        \nВозможные значения
        status\n  - ok - все ok\n  - source - не найден аккаунт отправителя\n  - destination
        - не найден аккаунт получателя\n  - negative_amount - недопустимое значение
        суммы перевода\n  - no_balance - не хватает средств на аккаунте отправителя\n
        \ - 500 - ошибка на сервере\n\nЕсли транзакция успешна - возвращаются актуальные
        значения баланса на аккаунтах\nЕсли транзакция не успешна - возвращаются значения,
        актуальные на момент запроса и amount = 0\nЕсли перевод не был сделан, то
        amount = 0\n\nЕсли аккаунт не найден, то в ответе будет пустая строка в качестве
        его номера и 0 баланс\n"
      parameters:
      - name: source_account_number
        in: query
        description: Номер счета отправителя
        schema:
          type: string
      - name: destination_account_number
        in: query
        description: Номер счета получателя
        schema:
          type: string
      - name: amount
        in: query
        description: Сумма перевода
        schema:
          type: integer
      responses:
        '200':
          description: Перевод cредств между аккаунтами
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  transfer:
                    type: object
                    properties:
                      uuid:
                        type: string
                      source_account_number:
                        type: string
                      source_balance:
                        type: integer
                      destination_account_number:
                        type: string
                      destination_balance:
                        type: integer
                      amount:
                        type: integer
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: rest-bank.netlify.ru
